apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocdhooks
  namespace: argocd
spec:
  project: myproj
  source:
    repoURL: https://github.com/amitopenwriteup/argocdhooks.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
