---
# PreSync Hook: Create database secret
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: database
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_DATABASE: "wordpress"
  MYSQL_USER: "wpuser"
  MYSQL_PASSWORD: "wppassword"
---
# PreSync Hook: Create PHP secret
apiVersion: v1
kind: Secret
metadata:
  name: php-secret
  namespace: php
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
type: Opaque
stringData:
  DB_HOST: "mysql-service.database.svc.cluster.local"
  DB_NAME: "wordpress"
  DB_USER: "wpuser"
  DB_PASSWORD: "wppassword"
---
# PreSync Hook: Create WordPress secret
apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  namespace: wordpress
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
type: Opaque
stringData:
  WORDPRESS_DB_HOST: "mysql-service.database.svc.cluster.local"
  WORDPRESS_DB_NAME: "wordpress"
  WORDPRESS_DB_USER: "wpuser"
  WORDPRESS_DB_PASSWORD: "wppassword"
---
# Sync Wave -3: Namespaces
apiVersion: v1
kind: Namespace
metadata:
  name: database
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
---
apiVersion: v1
kind: Namespace
metadata:
  name: php
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
---
apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
---
# Sync Wave -2: PersistentVolume for database
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-database
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/database
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-worker2
---
# Sync Wave -2: PersistentVolume for WordPress
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-wordpress
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/wordpress
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-worker
---
# Sync Wave -1: PersistentVolumeClaim for database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Sync Wave -1: PersistentVolumeClaim for WordPress
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wb-pvc
  namespace: wordpress
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
